AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nanami-dashboard
  
  Sample SAM Template for nanami-dashboard

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: nanami-dashboard
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: any
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          POKELOC: https://40kcasg670.execute-api.ap-northeast-1.amazonaws.com/Prod/
          POKELOCID: d7e20e2ea5845e71d271e196a1b32e84
          MOMOCHI: https://x38q3eq72c.execute-api.ap-northeast-1.amazonaws.com/Prod/co2/last

Outputs:
  API:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  Function:
    Value: !GetAtt Function.Arn
  FunctionIamRole:
    Value: !GetAtt FunctionRole.Arn
